// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cjkuvjzztigzlohtbdjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqa3V2anp6dGlnemxvaHRiZGp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1Nzc3NzEsImV4cCI6MjA2NzE1Mzc3MX0.MFk7pmTTPNZmlPvC4X9v2Gxi4ipal7hCpBmt6AB8hfA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});