import { CVData } from '@/types/cv.types';

export function getEmptyCV(): CVData {
  return {
    personalInfo: {
      firstName: '',
      lastName: '',
      title: '',
      email: '',
      phone: '',
      location: {
        city: '',
        state: '',
        country: '',
      },
      summary: '',
      links: [],
    },
    sections: {
      experience: [],
      education: [],
      skills: [],
      projects: [],
      certifications: [],
      languages: [],
      awards: [],
      publications: [],
      references: [],
    },
    metadata: {
      templateSlug: 'modern',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      version: 1,
      isPublic: false,
    },
  };
}

export function getSampleData(): CVData {
  return {
    personalInfo: {
      firstName: 'John',
      lastName: 'Doe',
      title: 'Senior Software Engineer',
      email: 'john.doe@example.com',
      phone: '+1 (555) 123-4567',
      location: {
        city: 'San Francisco',
        state: 'CA',
        country: 'USA',
      },
      summary: 'Experienced software engineer with 8+ years of expertise in building scalable web applications and leading cross-functional teams. Passionate about clean code, best practices, and mentoring junior developers.',
      links: [
        { type: 'linkedin', url: 'https://linkedin.com/in/johndoe', label: 'LinkedIn' },
        { type: 'github', url: 'https://github.com/johndoe', label: 'GitHub' },
        { type: 'portfolio', url: 'https://johndoe.dev', label: 'Portfolio' },
      ],
    },
    sections: {
      experience: [
        {
          id: '1',
          company: 'Tech Innovations Inc.',
          position: 'Senior Software Engineer',
          location: 'San Francisco, CA',
          startDate: '2020-03',
          endDate: undefined,
          current: true,
          description: 'Leading development of microservices architecture and mentoring team of 5 engineers.',
          highlights: [
            'Architected and implemented a microservices platform serving 2M+ daily users',
            'Reduced API response time by 40% through optimization and caching strategies',
            'Mentored 5 junior developers and conducted technical interviews',
            'Led migration from monolithic to microservices architecture',
          ],
        },
        {
          id: '2',
          company: 'Digital Solutions Corp',
          position: 'Full Stack Developer',
          location: 'New York, NY',
          startDate: '2017-06',
          endDate: '2020-02',
          current: false,
          description: 'Developed and maintained full-stack web applications using React and Node.js.',
          highlights: [
            'Built 3 production-ready web applications from scratch',
            'Implemented CI/CD pipelines reducing deployment time by 60%',
            'Collaborated with UX team to improve user engagement by 35%',
            'Optimized database queries resulting in 50% performance improvement',
          ],
        },
        {
          id: '3',
          company: 'StartUp Labs',
          position: 'Junior Developer',
          location: 'Boston, MA',
          startDate: '2015-08',
          endDate: '2017-05',
          current: false,
          description: 'Contributed to various web development projects and learned modern development practices.',
          highlights: [
            'Developed responsive web interfaces using HTML, CSS, and JavaScript',
            'Participated in agile development process and daily standups',
            'Fixed bugs and implemented feature requests from clients',
            'Learned and applied best practices in code review and testing',
          ],
        },
      ],
      education: [
        {
          id: '1',
          institution: 'Massachusetts Institute of Technology',
          degree: 'Master of Science',
          field: 'Computer Science',
          location: 'Cambridge, MA',
          startDate: '2013-09',
          endDate: '2015-05',
          current: false,
          gpa: '3.9/4.0',
          honors: ['Cum Laude', 'Dean\'s List'],
          coursework: ['Advanced Algorithms', 'Distributed Systems', 'Machine Learning', 'Software Engineering'],
        },
        {
          id: '2',
          institution: 'University of California, Berkeley',
          degree: 'Bachelor of Science',
          field: 'Computer Science',
          location: 'Berkeley, CA',
          startDate: '2009-09',
          endDate: '2013-05',
          current: false,
          gpa: '3.7/4.0',
          honors: ['Honor Roll'],
          coursework: ['Data Structures', 'Operating Systems', 'Database Systems', 'Web Development'],
        },
      ],
      skills: [
        {
          id: '1',
          category: 'Programming Languages',
          skills: [
            { name: 'JavaScript/TypeScript', level: 'expert', rating: 5 },
            { name: 'Python', level: 'advanced', rating: 4 },
            { name: 'Java', level: 'advanced', rating: 4 },
            { name: 'Go', level: 'intermediate', rating: 3 },
          ],
        },
        {
          id: '2',
          category: 'Frontend',
          skills: [
            { name: 'React', level: 'expert', rating: 5 },
            { name: 'Next.js', level: 'expert', rating: 5 },
            { name: 'Vue.js', level: 'advanced', rating: 4 },
            { name: 'CSS/Tailwind', level: 'expert', rating: 5 },
          ],
        },
        {
          id: '3',
          category: 'Backend',
          skills: [
            { name: 'Node.js', level: 'expert', rating: 5 },
            { name: 'Express', level: 'expert', rating: 5 },
            { name: 'Django', level: 'advanced', rating: 4 },
            { name: 'PostgreSQL', level: 'advanced', rating: 4 },
          ],
        },
        {
          id: '4',
          category: 'Tools & Technologies',
          skills: [
            { name: 'Git', level: 'expert', rating: 5 },
            { name: 'Docker', level: 'advanced', rating: 4 },
            { name: 'Kubernetes', level: 'intermediate', rating: 3 },
            { name: 'AWS', level: 'advanced', rating: 4 },
          ],
        },
      ],
      projects: [
        {
          id: '1',
          name: 'E-Commerce Platform',
          description: 'Full-stack e-commerce platform with real-time inventory management and payment processing.',
          technologies: ['React', 'Node.js', 'PostgreSQL', 'Stripe API', 'Redis'],
          startDate: '2023-01',
          endDate: '2023-06',
          url: 'https://example-ecommerce.com',
          githubUrl: 'https://github.com/johndoe/ecommerce-platform',
          highlights: [
            'Handled 10,000+ daily transactions',
            'Implemented real-time inventory tracking',
            'Integrated multiple payment gateways',
            '99.9% uptime achievement',
          ],
        },
        {
          id: '2',
          name: 'Task Management System',
          description: 'Collaborative task management tool with real-time updates and team collaboration features.',
          technologies: ['Vue.js', 'Express', 'MongoDB', 'Socket.io', 'JWT'],
          startDate: '2022-06',
          endDate: '2022-09',
          url: 'https://taskmanager.example.com',
          githubUrl: 'https://github.com/johndoe/task-manager',
          highlights: [
            'Real-time collaboration for teams',
            'Drag-and-drop kanban boards',
            'Advanced filtering and search',
            'Email and Slack notifications',
          ],
        },
      ],
      certifications: [
        {
          id: '1',
          name: 'AWS Certified Solutions Architect',
          issuer: 'Amazon Web Services',
          date: '2022-08',
          expiryDate: '2025-08',
          credentialId: 'AWS-123456',
          url: 'https://aws.amazon.com/certification/',
        },
        {
          id: '2',
          name: 'Google Cloud Professional Developer',
          issuer: 'Google Cloud',
          date: '2021-11',
          expiryDate: '2024-11',
          credentialId: 'GCP-789012',
          url: 'https://cloud.google.com/certification/',
        },
      ],
      languages: [
        {
          id: '1',
          language: 'English',
          proficiency: 'native',
        },
        {
          id: '2',
          language: 'Spanish',
          proficiency: 'professional',
        },
        {
          id: '3',
          language: 'Mandarin',
          proficiency: 'conversational',
        },
      ],
      awards: [
        {
          id: '1',
          title: 'Best Innovation Award',
          issuer: 'Tech Innovations Inc.',
          date: '2023-12',
          description: 'Recognized for developing an innovative solution that improved system efficiency by 50%',
        },
        {
          id: '2',
          title: 'Employee of the Year',
          issuer: 'Digital Solutions Corp',
          date: '2019-12',
          description: 'Awarded for exceptional performance and contributions to team success',
        },
      ],
      publications: [],
      references: [],
    },
    metadata: {
      templateSlug: 'modern',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      version: 1,
      isPublic: false,
    },
  };
}