import { CVData } from '@/types/cv.types';

export function getEmptyCV(): CVData {
  return {
    personalInfo: {
      firstName: '',
      lastName: '',
      title: '',
      email: '',
      phone: '',
      location: {
        city: '',
        state: '',
        country: '',
      },
      summary: '',
      links: [],
    },
    sections: {
      experience: [],
      education: [],
      skills: [],
      projects: [],
      certifications: [],
      languages: [],
      awards: [],
      publications: [],
      references: [],
    },
    metadata: {
      templateSlug: 'modern',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      version: 1,
      isPublic: false,
    },
  };
}

export function getSampleData(): CVData {
  return {
    personalInfo: {
      firstName: 'Saurav',
      lastName: 'Adhikari',
      title: 'Senior Talent Acquisition Specialist | HR Professional',
      email: 'saurav.adhikari@recruitnepal.com',
      phone: '+977 98XXXXXXXX',
      location: {
        city: 'Kathmandu',
        state: 'Bagmati',
        country: 'Nepal',
      },
      photo: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgdmlld0JveD0iMCAwIDIwMCAyMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxjaXJjbGUgY3g9IjEwMCIgY3k9IjEwMCIgcj0iMTAwIiBmaWxsPSIjNDc1NTY5Ii8+CjxwYXRoIGQ9Ik0xMDAgNjBDODYuNzQ1MiA2MCA3NiA3MC43NDUyIDc2IDg0Qzc2IDk3LjI1NDggODYuNzQ1MiAxMDggMTAwIDEwOEMxMTMuMjU1IDEwOCAxMjQgOTcuMjU0OCAxMjQgODRDMTI0IDcwLjc0NTIgMTEzLjI1NSA2MCAxMDAgNjBaIiBmaWxsPSIjRTVFN0VCIi8+CjxwYXRoIGQ9Ik01MCAxNTBDNTAgMTMwIDcwIDEyMCAxMDAgMTIwQzEzMCAxMjAgMTUwIDEzMCAxNTAgMTUwVjIwMEg1MFYxNTBaIiBmaWxsPSIjRTVFN0VCIi8+Cjwvc3ZnPg==',
      summary: 'Experienced Talent Acquisition Specialist with 7+ years of expertise in recruiting top talent across IT, Finance, and Engineering sectors in Nepal and internationally. Passionate about connecting exceptional candidates with transformative career opportunities. Specialized in technical recruitment, employer branding, and building strong talent pipelines for leading organizations.',
      links: [
        { type: 'linkedin', url: 'https://www.linkedin.com/in/sauravrecruiter/', label: 'LinkedIn' },
        { type: 'other', url: 'https://recruitnepal.com', label: 'Recruit Nepal' },
        { type: 'other', url: 'mailto:saurav@recruitnepal.com', label: 'Email' },
      ],
    },
    sections: {
      experience: [
        {
          id: '1',
          company: 'Recruit Nepal Pvt. Ltd.',
          position: 'Senior Talent Acquisition Specialist',
          location: 'Kathmandu, Nepal',
          startDate: '2021-01',
          endDate: undefined,
          current: true,
          description: 'Leading recruitment initiatives for top-tier IT and finance companies in Nepal and globally.',
          highlights: [
            'Successfully placed 200+ candidates in leading tech companies across Nepal and abroad',
            'Reduced time-to-hire by 35% through streamlined recruitment processes',
            'Built talent pipeline of 5000+ qualified candidates across various sectors',
            'Achieved 95% client satisfaction rate through quality placements',
          ],
        },
        {
          id: '2',
          company: 'Global Tech Solutions Nepal',
          position: 'HR Manager & Talent Acquisition Lead',
          location: 'Kathmandu, Nepal',
          startDate: '2018-06',
          endDate: '2020-12',
          current: false,
          description: 'Managed end-to-end recruitment and HR operations for a 300+ employee tech company.',
          highlights: [
            'Hired 150+ technical professionals including developers, QA, and DevOps engineers',
            'Implemented ATS system resulting in 40% improvement in recruitment efficiency',
            'Developed employer branding strategy increasing applications by 60%',
            'Conducted 500+ interviews and technical assessments',
          ],
        },
        {
          id: '3',
          company: 'Himalayan Bank Limited',
          position: 'HR Executive - Recruitment',
          location: 'Kathmandu, Nepal',
          startDate: '2015-08',
          endDate: '2018-05',
          current: false,
          description: 'Managed recruitment for banking sector positions across multiple branches.',
          highlights: [
            'Recruited 100+ banking professionals including relationship managers and operations staff',
            'Organized campus recruitment drives in 15+ universities across Nepal',
            'Maintained employee database and HR information system',
            'Coordinated with department heads for manpower planning and budgeting',
          ],
        },
      ],
      education: [
        {
          id: '1',
          institution: 'Tribhuvan University',
          degree: 'Master of Business Administration',
          field: 'Human Resource Management',
          location: 'Kathmandu, Nepal',
          startDate: '2013-09',
          endDate: '2015-08',
          current: false,
          gpa: '3.8/4.0',
          honors: ['Distinction', 'Best HR Project Award'],
          coursework: ['Strategic HRM', 'Organizational Behavior', 'Talent Management', 'Compensation Management'],
        },
        {
          id: '2',
          institution: 'Kathmandu University',
          degree: 'Bachelor of Business Administration',
          field: 'Human Resource Management',
          location: 'Dhulikhel, Nepal',
          startDate: '2009-08',
          endDate: '2013-07',
          current: false,
          gpa: '3.6/4.0',
          honors: ['Dean\'s List'],
          coursework: ['Business Management', 'Industrial Psychology', 'Labor Laws', 'Recruitment & Selection'],
        },
      ],
      skills: [
        {
          id: '1',
          category: 'Recruitment & Sourcing',
          skills: [
            { name: 'Technical Recruitment', level: 'expert', rating: 5 },
            { name: 'Executive Search', level: 'expert', rating: 5 },
            { name: 'Campus Recruitment', level: 'advanced', rating: 4 },
            { name: 'Boolean Search', level: 'expert', rating: 5 },
          ],
        },
        {
          id: '2',
          category: 'HR Tools & ATS',
          skills: [
            { name: 'LinkedIn Recruiter', level: 'expert', rating: 5 },
            { name: 'Workday HCM', level: 'advanced', rating: 4 },
            { name: 'BambooHR', level: 'expert', rating: 5 },
            { name: 'Greenhouse ATS', level: 'advanced', rating: 4 },
          ],
        },
        {
          id: '3',
          category: 'HR Management',
          skills: [
            { name: 'Talent Pipeline Building', level: 'expert', rating: 5 },
            { name: 'Employer Branding', level: 'expert', rating: 5 },
            { name: 'Compensation & Benefits', level: 'advanced', rating: 4 },
            { name: 'Performance Management', level: 'advanced', rating: 4 },
          ],
        },
        {
          id: '4',
          category: 'Soft Skills',
          skills: [
            { name: 'Stakeholder Management', level: 'expert', rating: 5 },
            { name: 'Negotiation', level: 'expert', rating: 5 },
            { name: 'Cross-cultural Communication', level: 'advanced', rating: 4 },
            { name: 'Team Leadership', level: 'advanced', rating: 4 },
          ],
        },
      ],
      projects: [
        {
          id: '1',
          name: 'E-Commerce Platform',
          description: 'Full-stack e-commerce platform with real-time inventory management and payment processing.',
          technologies: ['React', 'Node.js', 'PostgreSQL', 'Stripe API', 'Redis'],
          startDate: '2023-01',
          endDate: '2023-06',
          url: 'https://example-ecommerce.com',
          githubUrl: 'https://github.com/johndoe/ecommerce-platform',
          highlights: [
            'Handled 10,000+ daily transactions',
            'Implemented real-time inventory tracking',
            'Integrated multiple payment gateways',
            '99.9% uptime achievement',
          ],
        },
        {
          id: '2',
          name: 'Task Management System',
          description: 'Collaborative task management tool with real-time updates and team collaboration features.',
          technologies: ['Vue.js', 'Express', 'MongoDB', 'Socket.io', 'JWT'],
          startDate: '2022-06',
          endDate: '2022-09',
          url: 'https://taskmanager.example.com',
          githubUrl: 'https://github.com/johndoe/task-manager',
          highlights: [
            'Real-time collaboration for teams',
            'Drag-and-drop kanban boards',
            'Advanced filtering and search',
            'Email and Slack notifications',
          ],
        },
      ],
      certifications: [
        {
          id: '1',
          name: 'AWS Certified Solutions Architect',
          issuer: 'Amazon Web Services',
          date: '2022-08',
          expiryDate: '2025-08',
          credentialId: 'AWS-123456',
          url: 'https://aws.amazon.com/certification/',
        },
        {
          id: '2',
          name: 'Google Cloud Professional Developer',
          issuer: 'Google Cloud',
          date: '2021-11',
          expiryDate: '2024-11',
          credentialId: 'GCP-789012',
          url: 'https://cloud.google.com/certification/',
        },
      ],
      languages: [
        {
          id: '1',
          language: 'English',
          proficiency: 'native',
        },
        {
          id: '2',
          language: 'Spanish',
          proficiency: 'professional',
        },
        {
          id: '3',
          language: 'Mandarin',
          proficiency: 'conversational',
        },
      ],
      awards: [
        {
          id: '1',
          title: 'Best Innovation Award',
          issuer: 'Tech Innovations Inc.',
          date: '2023-12',
          description: 'Recognized for developing an innovative solution that improved system efficiency by 50%',
        },
        {
          id: '2',
          title: 'Employee of the Year',
          issuer: 'Digital Solutions Corp',
          date: '2019-12',
          description: 'Awarded for exceptional performance and contributions to team success',
        },
      ],
      publications: [],
      references: [],
    },
    metadata: {
      templateSlug: 'modern',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      version: 1,
      isPublic: false,
    },
  };
}